server:
  port: ${server.users.port}
  name: users

security:
  cluster-key: "super-secret-internal-only-cluster-key-for-users"

spring:
  config:
    import: "classpath:/${APP_ENV:dev}.yaml"
  datasource:
    url: jdbc:mariadb://localhost:3306/usersdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: never