#Gateway microservice
server:
  port: ${server.gateway.port}

spring:
  config:
    import: "classpath:/${APP_ENV:dev}.yaml"

app:
  security:
    cors:
#      allowed-origins: []
      allowed-headers: ["Content-Type", "Cookie", "Accept", "Authorization"]
      exposed-headers: ["X-log-ID"]