server:
  port: ${server.auth.port}

spring:
  config:
    import: "classpath:/${APP_ENV:dev}.yaml"

security:
  fingerprint: Temporary-key-for-dev-environment-only
  private-key-path: "${user.home}/keys/private_key_pkcs8.pem"
  public-key-path: "${user.home}/keys/public_key.pem"

jwt:
  secret: Temporary-key-for-dev-environment-only
  access:
    expiry: 300000 #5 minutes
  refresh:
    expiry: 3600000 #1 hour

internal:
  auth: false