server:
  port: ${server.transactions.port}
  name: txn

security:
  cluster-key: "super-secret-internal-only-cluster-key-for-txn"

spring:
  config:
    import: "classpath:/${APP_ENV:dev}.yaml"

  datasource:
    url: jdbc:mariadb://localhost:3306/transactionsdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: never